version: "3.7"
services:
  dashboard:
    image: "d_wise"
    build: .
    ports:
      - "7000:80"
    environment:
      PROD_DATA_FILE: ./data/cleaned_data.csv
      PROD_WORD_FILE: ./data/word_list
      PROD_HASHTAG_FILE: ./data/hashtag_list
      DEV_DATA_FILE: ./tests/test_data/dev.csv
      DEV_WORD_FILE: ./tests/test_data/dev_word_list
      DEV_HASHTAG_FILE: ./tests/test_data/dev_hashtag_list
      TEST_DATA_FILE: ./tests/test_data/test.csv
      TEST_WORD_FILE: ./tests/test_data/test_word_list
      TEST_HASHTAG_FILE: ./tests/test_data/test_hashtag_list
      MODE: production