version: "3.7"
services:
  dashboard:
    image: "d_wise"
    build: .
    ports:
      - "7000:80"
    environment:
      PROD_FILE: ./data/mini.csv
      DEV_FILE: ./data/mini.csv
      TEST_FILE: ./data/mini.csv
      MODE: development